// Generates docs/COVERAGE.md from the catalog plus real validation results.
// Run with: npm run coverage:docs
import { writeFileSync } from 'node:fs';
import { it } from 'vitest';
import { CATALOG, MODULES } from '../src/content/catalog';
import type { Unit } from '../src/content/types';
import { validateUnits } from '../src/content/validate.node';

const mods = import.meta.glob<{ default: Unit }>('../src/content/units/*/*.ts', { eager: true });

it('writes docs/COVERAGE.md', async () => {
  const units = Object.values(mods).map((m) => m.default);
  const reports = await validateUnits(units);
  const yes = '✅';
  const no = '⬜';
  const bad = '❌';
  const rows: string[] = [];
  let full = 0;
  const perModule: Record<string, { total: number; done: number }> = {};
  for (const c of CATALOG) {
    const r = reports[c.id];
    perModule[c.module] ??= { total: 0, done: 0 };
    perModule[c.module].total++;
    let viz = no;
    let drills = no;
    let boss = no;
    let status = 'not started';
    if (r) {
      viz = r.viz.length ? bad : yes;
      drills = r.drills.length || r.other.length ? bad : yes;
      boss = r.boss.length ? bad : yes;
      const ok = viz === yes && drills === yes && boss === yes;
      status = ok ? 'done' : 'failing checks';
      if (ok) {
        full++;
        perModule[c.module].done++;
      }
    }
    rows.push(`| ${MODULES.find((m) => m.id === c.module)!.code} | ${c.topic} | ${c.title} | \`${c.id}\` | ${viz} | ${drills} | ${boss} | ${status} |`);
  }
  const summary = MODULES.map((m) => `| ${m.code} ${m.title} | ${perModule[m.id].done} / ${perModule[m.id].total} |`).join('\n');
  const md = `# Coverage

Generated by \`npm run coverage:docs\` from \`src/content/catalog.ts\` and **automated validation** — a cell is ✅ only when the checks below actually pass.

- **Visualizer**: runs on its default input and every preset, produces well-formed frames, and its result matches an independent reference implementation (where one is given).
- **Drills**: predict question valid; practice solution passes all tests; the level-2 skeleton and level-3 starter fail; blanks rebuild the solution; buggy debug code fails and the fixed version passes.
- **Boss**: reference solution passes, starter fails, two tiered hints present.

Legend: ✅ verified · ❌ present but failing checks · ⬜ not started

**${full} / ${CATALOG.length} concepts fully done.**

| Module | Done |
|---|---|
${summary}

| Mod | Topic | Concept | id | Visualizer | Drills | Boss | Status |
|---|---|---|---|---|---|---|---|
${rows.join('\n')}
`;
  writeFileSync(new URL('../docs/COVERAGE.md', import.meta.url), md);
});
